name: Build and Deploy Next.js + Prisma to Azure Web App - notifyNL-verification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install dependencies (production)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5️⃣ Run Prisma migrations (production)
      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # 6️⃣ Optional: Run tests
      - name: Run tests
        run: npm run test --if-present

      # 7️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 8️⃣ Deploy only the required files to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'notifyNL-verification-service'
          slot-name: 'Production'
          package: |
            .next
            package.json
            package-lock.json
            node_modules
