name: Build and deploy Node.js app to Azure Web App - notifyNL-verification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # Cache Next.js build
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      # Cache node_modules
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install dependencies
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      # Generate Prisma client
      - name: Generate Prisma client
        run: npx prisma generate

      # Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Upload artifact including only necessary files
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next
            prisma
            package.json
            package-lock.json
            public
            next.config.js
            server.js
            app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Ensure DB exists
      - name: Ensure database exists
        run: |
          export DB_NAME=$(echo ${{ secrets.DATABASE_URL }} | sed -E 's!.*/([a-zA-Z0-9_-]+)(\?.*)?$!\1!')
          export BASE_URL=$(echo ${{ secrets.DATABASE_URL }} | sed -E "s/\/$DB_NAME.*//")
          psql "$BASE_URL/postgres" -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || psql "$BASE_URL/postgres" -c "CREATE DATABASE \"$DB_NAME\""
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Apply Prisma migrations
      - name: Apply Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E93E7279BA514AE99AD31854D1FCDF19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B11872507EDA4F2D963A210A94FD4ABD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DB82D79155A4634B13DD483FE2D6961 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'notifyNL-verification-service'
          slot-name: 'Production'
          package: .