name: Build and deploy Node.js app to Azure Web App - notifyNL-verification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Drop and recreate the database
        run: |
          export DB_NAME=$(echo ${{ secrets.DATABASE_URL }} | sed -E 's!.*/([a-zA-Z0-9_-]+)(\?.*)?$!\1!')
          export BASE_URL=$(echo ${{ secrets.DATABASE_URL }} | sed -E "s/\/$DB_NAME.*//")

          echo "🔍 Extracted DB_NAME=$DB_NAME"
          echo "💥 Terminating active connections to $DB_NAME..."

          # Terminate all connections except this one
          psql "$BASE_URL/postgres" -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${DB_NAME}' AND pid <> pg_backend_pid();"

          echo "🧨 Dropping database $DB_NAME..."
          psql "$BASE_URL/postgres" -c "DROP DATABASE IF EXISTS \"$DB_NAME\";"

          echo "📦 Recreating database $DB_NAME..."
          psql "$BASE_URL/postgres" -c "CREATE DATABASE \"$DB_NAME\";"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Reset DB and apply migrations
        run: npx prisma migrate reset --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E93E7279BA514AE99AD31854D1FCDF19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B11872507EDA4F2D963A210A94FD4ABD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DB82D79155A4634B13DD483FE2D6961 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'notifyNL-verification-service'
          slot-name: 'Production'
          package: .